title: The Internship Prep
author: Martin Gonzales
email: mgonzales0024@gmail.com
description: Basic stuffs required before entering an Internship Program.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
